[package]
name = "thread-opt"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
compact_str = "0.8.1"
dumpsys-rs = { git = "https://github.com/reigadegr/dumpsys-rs" }
flexi_logger = "0.29.8"
flume = "0.11.1"
hashbrown = "0.15.2"
libc = "0.2.169"
log = "0.4.25"
once_cell = "1.20.2"

[build-dependencies]
anyhow = "1.0.95"
vergen = { version = "9.0.4", features = ["build", "cargo", "rustc", "si"] }

[profile.dev]
debug = 0
debug-assertions = true
panic = "abort"
incremental = false

[profile.release]
overflow-checks = false
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true
debug = 0
debug-assertions = false
incremental = false
