[package]
name = "thread-opt"
version = "1.9.1"
edition = "2021"
description = "The Hard Affinity policy binds threads to target cores in gaming."
authors = ["reigadegr"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/reigadegr/thread-opt"

[[bin]]
name = "thread-opt"
path = "src/main.rs"

# [lib]
# name = "thread_opt"
# path = "src/lib.rs"
# crate-type = ["staticlib", "cdylib"]

[dependencies]
anyhow = { version = "1.0.95", default-features = false }
atoi = { version = "2.0.0", default-features = false }
compact_str = { version = "0.9.0", default-features = false }
dumpsys-rs = { git = "https://github.com/reigadegr/dumpsys-rs" }
hashbrown = { version = "0.15.2", default-features = false, features = [
    "default-hasher",
    "inline-more",
] }
inotify = { version = "0.11.0", default-features = false }
itoa = { version = "1.0.14", features = ["no-panic"] }
libc = { version = "0.2.170", default-features = false }
likely_stable = "0.1.3"
log = "0.4.26"
mimalloc = { version = "0.1.43", features = ["local_dynamic_tls", "no_thp", "override"] }
minstant = "0.1.7"
once_cell = { version = "1.20.3", default-features = false }
stringzilla = "3.12.0"
tklog = "0.2.9"

[build-dependencies]
anyhow = "1.0.95"
vergen = { version = "9.0.4", features = ["build", "cargo", "rustc", "si"] }

[profile.dev]
debug = 0
debug-assertions = true
panic = "abort"
incremental = false

[profile.release]
overflow-checks = false
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true
debug = 0
debug-assertions = false
incremental = false
