[package]
name = "thread-opt"
version = "1.8.0"
edition = "2024"
description = "The Hard Affinity policy binds threads to target cores in gaming."
authors = ["reigadegr"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/reigadegr/thread-opt"

[features]
default = ["std"]
std = []
net = []

[[bin]]
name = "thread-opt"
path = "src/main.rs"

# [lib]
# name = "thread_opt"
# path = "src/lib.rs"
# crate-type = ["staticlib", "cdylib"]

[dependencies]
anyhow = "1.0.95"
atoi = "2.0.0"
compact_str = "0.8.1"
dumpsys-rs = { git = "https://github.com/reigadegr/dumpsys-rs" }
hashbrown = "0.15.2"
libc = "0.2.169"
likely_stable = "0.1.3"
log = "0.4.25"
minstant = "0.1.7"
no_std_io = "0.6.0"
once_cell = "1.20.2"
spin_sleep = "1.3.0"
tklog = "0.2.9"

[build-dependencies]
anyhow = "1.0.95"
vergen = { version = "9.0.4", features = ["build", "cargo", "rustc", "si"] }

[profile.dev]
debug = 0
debug-assertions = true
panic = "abort"
incremental = false

[profile.release]
overflow-checks = false
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true
debug = 0
debug-assertions = false
incremental = false
