[[comm_match]]
packages = [
    "com.miHoYo.Yuanshen",
    "com.miHoYo.GenshinImpact",
    "com.miHoYo.ys.bilibili",
    "com.miHoYo.yuanshencb",
    "com.miHoYo.hkrpg",
    "com.miHoYo.hkrpg.bilibili",
    "com.HoYoverse.hkrpgoversea",
    "com.miHoYo.hkrpgcb",
    "com.tencent.tmgp.sgame",
    "com.miHoYo.Nap",
    "com.yongshi.tenojo.ys",
    "com.tencent.KiHan",
]
[comm_match.policy]
top = []
only6 = ["UnityGfx"]
only7 = ["UnityMain"]
middle = ["Thread-", "Job.Worker"]
background = []

[[comm_match]]
packages = ["com.kurogame.mingchao"]
[comm_match.policy]
top = ["Pool"]
only6 = ["RHIThread"]
only7 = ["GameThread"]
middle = ["RenderThread"]
background = []

[[comm_match]]
packages = ["com.netease.sky"]
[comm_match.policy]
top = ["Pool"]
only6 = []
only7 = ["MainThread"]
middle = ["JobThread"]
background = []

# 以下功能待开发中，不生效，暂时无需理会
[[usage_top1]]
packages = ["com.bf.sgs.hdexp"]
max_comm = ["GLThread-"]
max_comm_target = "Only7"
[usage_top1.policy]
top = []
only6 = ["GLThread"]
only7 = []
middle = []
background = []
