Simple thread prefix matching for Unity games

[[comm_match]]
packages = [
  "com.HoYoverse.hkrpgoversea",
  "com.hypergryph.arknights",
  "com.miHoYo.Nap",
  "com.miHoYo.Yuanshen",
  "com.miHoYo.GenshinImpact",
  "com.miHoYo.hkrpg",
  "com.miHoYo.hkrpg.bilibili",
  "com.miHoYo.hkrpgcb",
  "com.miHoYo.ys.bilibili",
  "com.miHoYo.yuanshencb",
  "com.mobile.legends",
  "com.tencent.KiHan",
  "com.tencent.tmgp.sgame",
  "com.yongshi.tenojo.ys",
]
[comm_match.policy]
top = []
dualo = ["UnityGfx"]
only7 = ["UnityMain"]
middle = ["Thread-", "Job.Worker"]
mono = []
background = []
core_closer = false

Simple thread prefix matching for UE games

[[comm_match]]
packages = ["com.kurogame.mingchao"]
[comm_match.policy]
top = ["Pool"]
dualo = ["RHIThread"]
only7 = ["GameThread"]
middle = ["RenderThread"]
mono = []
background = []
core_closer = false

Simple thread prefix matching for Sky: Children of the Light

[[comm_match]]
packages = ["com.netease.sky", "com.bilibili.fatego"]
[comm_match.policy]
top = []
dualo = []
only7 = ["MainThread", "UnityMain"]
middle = []
mono = ["JobThread", "Job.Worker"]
background = []
core_closer = true

Assign the highest-load GLThread to CPU7 for Cocos games like Three Kingdoms Kill and Time Hunter

[[usage_top1]]
packages = ["com.bf.sgs.hdexp", "com.yinhan.hunter.tx"]
max_comm = ["GLThread"]
max_comm_core = "Only7"
[usage_top1.policy]
top = []
dualo = []
only7 = []
middle = []
mono = []
background = []
core_closer = false

Rush Rally 3 optimization

[[usage_top1]]
packages = ["brownmonster.app.game.rushrally3"]
max_comm = ["Thread-"]
max_comm_core = "Only7"
[usage_top1.policy]
top = []
dualo = ["._RuMain"]
only7 = []
middle = ["mail-cmar"]
mono = []
background = []
core_closer = false

Optimize CPU7 binding for high-load threads in PUBG, etc.

[[usage_top1]]
packages = ["com.tencent.lzhx", "com.tencent.tmgp.pubgmhd"]
max_comm = ["Thread-"]
max_comm_core = "Only7"
[usage_top1.policy]
top = ["FAsync"]
dualo = ["RHIThread"]
only7 = []
middle = ["RenderThread"]
mono = []
background = []
core_closer = false

Infinity Nikki: Bind the heaviest GameThread to CPU7

[[usage_top1]]
packages = ["com.papegames.infinitynikki"]
max_comm = ["GameThread"]
max_comm_core = "Only7"
[usage_top1.policy]
top = []
dualo = ["RHIThread"]
only7 = []
middle = ["RenderThread"]
mono = []
background = []
core_closer = false

Bind UnityMain to CPU7 for COD and CF

[[usage_top1]]
packages = ["com.tencent.tmgp.cod", "com.tencent.tmgp.cf"]
max_comm = ["UnityMain"]
max_comm_core = "Only7"
[usage_top1.policy]
top = []
dualo = ["UnityGfx"]
only7 = []
middle = []
mono = []
background = ["Thread-"]
core_closer = false

Bind the second-highest load thread to CPU6 for specific games

[[usage_top1]]
packages = [
  "com.gameabc.sgspad",
  "com.tencent.lolm",
  "com.tencent.tmgp.speedmobile",
]
max_comm = ["Thread-"]
max_comm_core = "Dualo"
[usage_top1.policy]
top = []
dualo = []
only7 = ["UnityMain"]
middle = []
mono = []
background = ["Thread-"]
core_closer = false

Warzone-specific optimizations

[[usage_top1]]
packages = ["com.activision.callofduty.warzone"]
max_comm = ["Thread-"]
max_comm_core = "Dualo"
[usage_top1.policy]
top = []
dualo = []
only7 = ["WZM_Main"]
middle = ["Worker"]
mono = []
background = ["Thread-"]
core_closer = false

Special tuning for high-load thread pairs (Yanyun Sixteen Sounds)

[[usage_top2]]
packages = ["com.netease.yyslscn"]
max_comm = ["Thread-"]

Special tuning for high-load thread pairs (Eggy Party)

[[usage_top2]]
packages = ["com.netease.party"]
max_comm = ["MainThread"]
second_comm = ["Thread-"]

Special tuning for high-load thread pairs (Sausage Man, Chess games, etc.)

[[usage_top2]]
packages = [
  "com.galasports.operablebasketball.mi",
  "com.sofunny.Sausage",
  "com.tencent.jkchess",
]
max_comm = ["UnityMain"]
second_comm = ["Thread-"]

Special tuning for high-load thread pairs (Delta Force Mobile)

[[usage_top2]]
packages = ["com.tencent.tmgp.dfm"]
max_comm = ["GameThread"]
second_comm = ["RenderThread"]

